In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import cufflinks as cf

import plotly.plotly as py
import plotly.tools as tls
import plotly.graph_objs as go
import plotly.offline as po

orig_df = pd.read_csv("winning_booths_data.csv")
categories = ['no_category', 'fashion', 'home_garden', 'health_beauty', 'parts_accessories', 'jewelry_watches']
top_categories = ['No Category', 'Fashion', 'Home & Garden', 'Health & Beauty', 'Parts & Accessories', 'Jewelry & Watches']
df = orig_df[orig_df.featured_category_id.isin(top_categories)]

In [9]:
d = {name: pd.DataFrame() for name in categories where df.featured_category_id == name }

print(d)



#no_category = df[df.featured_category_id == 'No Category']
#fashion = df[df.featured_category_id == 'Fashion']
#home_garden = df[df.featured_category_id == 'Home & Garden']
#health_beauty = df[df.featured_category_id == 'Health & Beauty']
#parts_accessories = df[df.featured_category_id == 'Parts & Accessories']
#jewelry_watches = df[df.featured_category_id == 'Jewelry & Watches']
#categories = [no_category, fashion, home_garden, health_beauty, parts_accessories, jewelry_watches]

SyntaxError: invalid syntax (<ipython-input-9-d529132cc879>, line 1)

In [31]:
size = len(df)
for category in categories:
    if len(category) < size:
        size = len(category)
        
print(size)

3179
1902
1119
839
425
418
418

In [47]:
for category in categories:
    print(len(category))
    category = category.sample(size, replace=True)
    

#no_category = no_category.sample(size)
#fashion = fashion.sample(size)
#home_garden = home_garden.sample(size)
#ehalth_beauty = health_beauty.sample(size)
#parts_accessories = parts_accessories.sample(size)
#jewelry_watches = jewelry_watches.sample(size)

3179
3179
1902
3179
1119
3179
839
3179
425
3179
418
3179

In [18]:
for category in categories:
    pd.to_numeric(category.profit_estimate, errors='ignore')

In [23]:
for category in categories:
    category.groupby(['featured_category_id']).mean()


categories = [no_category, fashion, home_garden, health_beauty, parts_accessories, jewelry_watches]
print(categories)

[               id featured_category_id  profit_estimate  value_em created_at  \
5718   22111570.0          No Category           106.64  SEA_BASS    12/3/16
1558    6265331.0          No Category          1860.43   DOLPHIN    11/7/13
2074    8726807.0          No Category          2258.55   DOLPHIN     7/8/14
7822   28915482.0          No Category           832.07   DOLPHIN   11/17/17
6774   25621142.0          No Category            29.41    MINNOW    5/28/17
1154    4484577.0          No Category             5.15    MINNOW    9/27/12
8468   30905182.0          No Category            13.21    MINNOW     3/1/18
4368   16586162.0          No Category          1128.34  SEA_BASS    2/17/16
4164   16017518.0          No Category           105.62   DOLPHIN     1/9/16
394      333747.0          No Category          1712.20    MINNOW    1/22/10
6076   23298818.0          No Category          2149.30   DOLPHIN     2/2/17
3157   12480394.0          No Category           102.34    MINNOW     5/6/15
8923   32008868.0          No Category             0.68    MINNOW     5/1/18
8036   29716784.0          No Category           242.91  SEA_BASS   12/21/17
8611   31255787.0          No Category           157.65   DOLPHIN    3/21/18
3420   13451260.0          No Category            23.33    MINNOW    7/22/15
9381   33359117.0          No Category             5.48    MINNOW     7/8/18
10038  35038986.0          No Category            -2.78    MINNOW    10/5/18
6024   23159795.0          No Category           247.19    MINNOW    1/26/17
4339   16514982.0          No Category           413.44  SEA_BASS    2/12/16
3482   13666554.0          No Category           143.77   DOLPHIN     8/6/15
650      755090.0          No Category          5092.74   DOLPHIN   11/14/10
9768   34308104.0          No Category            20.98   DOLPHIN    8/25/18
4723   18585804.0          No Category           632.44   DOLPHIN     5/4/16
1137    4435375.0          No Category          -314.02    MINNOW    9/15/12
4597   17888661.0          No Category           -43.29    MINNOW    4/11/16
1280    5180461.0          No Category            22.02  SEA_BASS    2/14/13
1170    4562009.0          No Category           128.64    MINNOW   10/16/12
4975   19405751.0          No Category            51.90    MINNOW    6/26/16
8961   32138278.0          No Category            37.76    MINNOW     5/7/18
...           ...                  ...              ...       ...        ...
3737   14393300.0          No Category            32.30  SEA_BASS    9/27/15
1301    5269503.0          No Category            15.14  SEA_BASS     3/8/13
7905   29168316.0          No Category          1471.31   DOLPHIN   11/28/17
7799   28856350.0          No Category           595.15    MINNOW   11/14/17
3384   13345509.0          No Category           -84.77    MINNOW    7/13/15
3731   14379630.0          No Category            69.19    MINNOW    9/26/15
9494   33644414.0          No Category            41.68   DOLPHIN    7/22/18
10542  36077589.0          No Category            -0.36    MINNOW   11/30/18
9303   33161581.0          No Category            38.65  SEA_BASS    6/27/18
9631   33991693.0          No Category            44.49    MINNOW     8/8/18
8441   30859982.0          No Category             1.82    MINNOW    2/26/18
10239  35481952.0          No Category           622.53   DOLPHIN   10/29/18
3466   13616182.0          No Category            74.24  SEA_BASS     8/3/15
6712   25432271.0          No Category            55.10  SEA_BASS    5/19/17
160       50531.0          No Category           106.57    MINNOW     2/2/09
2465   10206406.0          No Category           519.67   DOLPHIN   10/28/14
7242   27027380.0          No Category          1410.07   DOLPHIN    8/12/17
9393   33381383.0          No Category          1375.74     WHALE     7/9/18
2086    8768347.0          No Category           515.47    MINNOW    7/11/14
2587   10606486.0          No Category           168.43  SEA_BASS    12/3/14
10533  36057267.0          No Category            -0.02    MINNOW   11/29/18
2372    9960957.0          No Category          1425.74   DOLPHIN    10/3/14
456      399885.0          No Category           572.58    MINNOW    3/13/10
9153   32679056.0          No Category            80.06  SEA_BASS     6/4/18
4661   18409166.0          No Category           746.69  SEA_BASS    4/22/16
4831   18918611.0          No Category            -1.31    MINNOW    5/26/16
10475  35949240.0          No Category            -0.59    MINNOW   11/24/18
10047  35058200.0          No Category            17.96  SEA_BASS    10/6/18
6885   25964332.0          No Category          1621.56     WHALE    6/15/17
2605   10655262.0          No Category           479.94   DOLPHIN    12/7/14

      first_sale days_to_sale days_as_user  profit_per_day    orders   ...    \
5718     2/22/17           81          745            0.14        84   ...
1558     1/23/15          442     1,867.00            1.00       604   ...
2074     7/31/14           23     1,624.00            1.39  1,257.00   ...
7822     12/7/17           20          396            2.10       324   ...
6774     8/16/17           80          569            0.05        15   ...
1154      9/9/13          347     2,273.00            0.00        80   ...
8468      3/3/18            2          292            0.05        10   ...
4368     2/25/16            8     1,035.00            1.09       106   ...
4164     1/12/16            3     1,074.00            0.10       104   ...
394       2/4/10           13     3,252.00            0.53       115   ...
6076      2/7/17            5          684            3.14       233   ...
3157      7/8/15           63     1,322.00            0.08        76   ...
8923     5/19/18           18          231            0.00         6   ...
8036    12/25/17            4          362            0.67        84   ...
8611     7/18/18          119          272            0.58        19   ...
3420      8/6/15           15     1,245.00            0.02        56   ...
9381     8/23/18           46          163            0.03         7   ...
10038    10/9/18            4           74           -0.04         4   ...
6024      2/1/17            6          691            0.36        60   ...
4339     2/18/16            6     1,040.00            0.40       371   ...
3482     5/22/16          290     1,230.00            0.12       406   ...
650     11/15/10            1     2,956.00            1.72  1,677.00   ...
9768    10/12/18           48          115            0.18         6   ...
4723     5/28/16           24          958            0.66        87   ...
1137    10/11/12           26     2,285.00           -0.14       192   ...
4597     7/17/16           97          981           -0.04        50   ...
1280      7/4/18     1,966.00     2,133.00            0.01        22   ...
1170      2/7/13          114     2,254.00            0.06       134   ...
4975     1/22/17          210          905            0.06        20   ...
8961     5/18/18           11          225            0.17         7   ...
...          ...          ...          ...             ...       ...   ...
3737     6/15/18          992     1,178.00            0.03        21   ...
1301     5/15/13           68     2,111.00            0.01       241   ...
7905    12/27/17           29          385            3.82       236   ...
7799     1/28/18           75          399            1.49        13   ...
3384     7/17/15            4     1,254.00           -0.07        39   ...
3731     4/10/16          197     1,179.00            0.06        46   ...
9494     7/25/18            3          149            0.28        76   ...
10542   12/16/18           16           18           -0.02         3   ...
9303     7/17/18           20          174            0.22        26   ...
9631     10/1/18           54          132            0.34         7   ...
8441      3/3/18            5          295            0.01         7   ...
10239   10/30/18            1           50           12.45       205   ...
3466      8/8/15            5     1,233.00            0.06       144   ...
6712      6/2/17           14          578            0.10        65   ...
160       4/5/09           62     3,606.00            0.03        99   ...
2465     7/27/15          272     1,512.00            0.34       239   ...
7242     10/1/17           50          493            2.86        77   ...
9393     7/12/18            3          162            8.49  1,586.00   ...
2086     7/14/14            3     1,621.00            0.32       117   ...
2587     12/6/14            3     1,476.00            0.11       317   ...
10533    12/3/18            4           19            0.00         1   ...
2372     1/12/15          101     1,537.00            0.93       114   ...
456      2/20/11          344     3,202.00            0.18       145   ...
9153     7/13/18           39          197            0.41        47   ...
4661     4/27/16            5          970            0.77       208   ...
4831      6/5/16           10          936            0.00        24   ...
10475   11/26/18            2           24           -0.02         4   ...
10047   11/30/18           55           73            0.25         6   ...
6885     7/30/17           45          551            2.94       492   ...
2605     2/16/15           71     1,472.00            0.33       161   ...

                 state  country items_for_sale view_count offers  \
5718                GA       US       1,106.00        427      0
1558    South Carolina       US              4        197      0
2074                GA       US              3        218      4
7822            fujian       CN              0         10      0
6774                CA       US             55         43      1
1154                MI       US            527        297      2
8468                Ny       US            333        148      2
4368                TX       US              2         44      5
4164                KY       US       1,141.00        241      2
394                 TX       US             98         48      0
6076                CA       US       3,646.00        634      6
3157                IL       US       1,913.00        547      3
8923      Lincolnshire       GB       1,518.00         52      0
8036                CA       US       1,336.00   1,081.00     12
8611                CO       US       2,284.00   1,370.00      2
3420                KS       US            450         96      1
9381   Šiauliai County       LT            478        165      1
10038            Dhaka       BD              2        211      1
6024          Kentucky       US            305        385      2
4339                WI       US            190        213     15
3482      Stara Zagora       BG              5         33      0
650                 TX       US             65        355      5
9768                TN       US            239        247      3
4723                IL       US              4          0      0
1137           Vilnius       LT       3,247.00   2,102.00      8
4597                AZ       US       1,013.00        765      3
1280                NJ       US              5        135      6
1170         East Java       ID             91        159      1
4975                NJ       US            450   1,398.00      0
8961                NY       US              3          6      0
...                ...      ...            ...        ...    ...
3737    South Carolina       US              3          4      1
1301                WA       US            103        107      1
7905                NY       US              9        616      3
7799                TN       US            216         72      1
3384                CT       US            201        218      2
3731                MN       US             16         15      0
9494                NC       US       5,122.00   1,710.00     23
10542               MO       US              5         38      3
9303                sc       US            478        138      1
9631                OH       US              3          2      0
8441         Louisiana       US             47        185      0
10239               LA       US            767   7,096.00    135
3466                AZ       US            958        499      1
6712          Chi?in?u       MD            591   1,323.00      9
160                 AZ       US             76         53      0
2465                MN       US       3,627.00   1,460.00      3
7242       UTTARAKHAND       IN       3,912.00   5,813.00      7
9393            Merkaz       IL              0  96,920.00    596
2086              OHIO       US            111         74      1
2587                GA       US            132        119      3
10533         brussels       BE             34        216      1
2372                ON       CA             41        212      3
456                 NY       US            783        125      1
9153                RI       US              3        273     27
4661                FL       US            378        671     18
4831                VA       US            785        315      0
10475          England       GB              6         66      4
10047               NJ       US             21        261      6
6885                IN       US            596   1,201.00      7
2605             Seoul       KR            923   1,609.00     12

      conversion_rate membership_level feedback  rate  rating
5718                0              0.0       10  0.12    4.40
1558                0              0.0       49  0.08    3.61
2074             0.02              0.0      108  0.09    4.91
7822                0              0.0       20  0.06    4.00
6774             0.02              0.0        1  0.07    5.00
1154             0.01              0.0       13  0.16    5.00
8468                0              0.0        1  0.10    5.00
4368             0.11              0.0       20  0.19    4.50
4164                0              0.0        8  0.08    4.75
394                 0              0.0       41  0.36    5.00
6076             0.01              3.0       20  0.09    3.00
3157             0.01              0.0        5  0.07    5.00
8923                0              0.0        1  0.17    4.00
8036             0.01              0.0       10  0.12    5.00
8611                0              0.0        1  0.05    5.00
3420             0.01              0.0        7  0.13    5.00
9381             0.01              0.0        0  0.00     NaN
10038               0              0.0        0  0.00     NaN
6024             0.01              0.0        2  0.03    5.00
4339              NAN              0.0       27  0.07    4.89
3482                0              0.0       18  0.04    5.00
650              0.01              0.0      213  0.13    4.68
9768             0.01              0.0        2  0.33    5.00
4723              NAN              0.0        9  0.10    4.11
1137                0              0.0       32  0.17    4.81
4597                0              0.0        7  0.14    4.71
1280             0.04              0.0        1  0.05    5.00
1170             0.03              0.0       13  0.10    4.54
4975                0              0.0        1  0.05    5.00
8961              NAN              0.0        0  0.00     NaN
...               ...              ...      ...   ...     ...
3737             0.02              0.0        4  0.19    5.00
1301             0.01              0.0       27  0.11    4.19
7905                0              2.0       33  0.14    4.88
7799             0.01              2.0        2  0.15    4.00
3384                0              0.0        1  0.03    5.00
3731                0              0.0        2  0.04    5.00
9494             0.01              0.0        7  0.09    4.43
10542            0.08              0.0        0  0.00     NaN
9303             0.01              0.0        0  0.00     NaN
9631                0              0.0        3  0.43    5.00
8441                0              0.0        2  0.29    5.00
10239            0.02              4.0       11  0.05    4.73
3466                0              0.0       13  0.09    4.69
6712              NAN              0.0        6  0.09    3.67
160                 0              0.0        6  0.06    4.33
2465                0              0.0       25  0.10    4.76
7242                0              0.0        7  0.09    3.29
9393                0              3.0       83  0.05    3.83
2086             0.01              0.0        7  0.06    4.43
2587              NAN              0.0       18  0.06    5.00
10533               0              0.0        0  0.00     NaN
2372             0.01              0.0        9  0.08    5.00
456              0.01              0.0       15  0.10    4.73
9153              0.1              0.0        5  0.11    5.00
4661              NAN              0.0       11  0.05    3.00
4831                0              0.0        2  0.08    5.00
10475            0.06              0.0        0  0.00     NaN
10047            0.02              0.0        0  0.00     NaN
6885             0.01              0.0       32  0.07    3.97
2605             0.01              0.0       14  0.09    5.00

[418 rows x 23 columns],                id featured_category_id  profit_estimate  value_em created_at  \
3522   13775291.0              Fashion           872.87   DOLPHIN    8/14/15
3815   14640917.0              Fashion           -93.37    MINNOW   10/14/15
7833   28936327.0              Fashion            34.09   DOLPHIN   11/18/17
5528   21398493.0              Fashion           167.76  SEA_BASS   10/23/16
2601   10641262.0              Fashion           362.83    MINNOW    12/6/14
9064   32432939.0              Fashion           111.01   DOLPHIN    5/22/18
2767   11215699.0              Fashion            -0.62    MINNOW    1/24/15
7714   28626048.0              Fashion            10.72    MINNOW    11/2/17
3901   14933205.0              Fashion           -16.03   DOLPHIN    11/4/15
444      381072.0              Fashion          1496.67    MINNOW    2/27/10
7310   27256956.0              Fashion            58.20    MINNOW    8/23/17
6863   25917637.0              Fashion            78.33    MINNOW    6/13/17
8025   29638330.0              Fashion          2937.41   DOLPHIN   12/17/17
9608   33959234.0              Fashion            83.60    MINNOW     8/6/18
4099   15742762.0              Fashion           842.83  SEA_BASS   12/22/15
9322   33203565.0              Fashion             9.00    MINNOW    6/29/18
1948    8165629.0              Fashion           332.16   DOLPHIN    5/29/14
8278   30422506.0              Fashion           204.55   DOLPHIN    1/31/18
6434   24535505.0              Fashion          1597.95   DOLPHIN     4/3/17
4394   16652890.0              Fashion           179.78  SEA_BASS    2/21/16
2322    9842088.0              Fashion          -903.83   DOLPHIN    9/21/14
2316    9821866.0              Fashion           141.88    MINNOW    9/18/14
3566   13884651.0              Fashion            86.80    MINNOW    8/22/15
10137  35230734.0              Fashion           386.59   DOLPHIN   10/16/18
9761   34281338.0              Fashion            13.76  SEA_BASS    8/23/18
2515   10372303.0              Fashion           441.78   DOLPHIN   11/13/14
4684   18471204.0              Fashion           100.01    MINNOW    4/26/16
5790   22385206.0              Fashion           114.10    MINNOW   12/16/16
635      720422.0              Fashion           652.85    MINNOW   10/25/10
1433    5763845.0              Fashion           513.16  SEA_BASS    7/12/13
...           ...                  ...              ...       ...        ...
1921    8037391.0              Fashion            87.34    MINNOW    5/19/14
4098   15742503.0              Fashion          -417.34   DOLPHIN   12/22/15

In [20]:
sum_values = sum([category.profit_estimate[0] for category in categories])

5240.952799043061

In [23]:


values = [(category.profit_estimate[0]/sum_values) *100 for category in categories]
print(values)

labels = top_categories

[7.456444867280903, 12.685622966936771, 15.671644533279025, 19.930017747101743, 28.01455387506308, 16.241716010338482]

In [1]:
fig = {
  "data": [
    {
      "values": values,
      "labels": labels,
      "marker": {'colors': ['rgb(33, 75, 99)',
                                  'rgb(79, 129, 102)',
                                  'rgb(151, 179, 100)',
                                  'rgb(175, 49, 35)',
                                  'rgb(36, 73, 147)']},
      "name": "values",
      "hoverinfo":"label+percent+name",
      "hole": .4,
      "type": "pie"
    }],
  "layout": {
        "title":"Mean Profit",
        "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": round(sum_values/6),
                
            }
        ]
    }
}
po.plot(fig, filename='donut.html')

NameError: name 'values' is not defined

In [10]:
data = [trace0, trace1, trace2, trace3, trace4, trace5]

layout = go.Layout(barmode='stack',title = 'Profit By Category')

figure = go.Figure(data=data, layout = layout)

po.plot(figure)

'file:///Users/kevin/data_analysis/temp-plot.html'

In [6]:

trace0 = go.Bar(
    x = no_category.index,
    y = no_category.id,
    name='No Category',
    opacity =.5
)

trace1 = go.Bar(
    x = fashion.index,
    y = fashion.id,
    name='Fashion',
    opacity =.5
)

trace2 = go.Bar(
    x = home_garden.index,
    y = home_garden.id,
    name='Home & Garden',
    opacity =.5
)

trace3 = go.Bar(
    x = health_beauty.index,
    y = health_beauty.id,
    name='Health & Beauty',
    opacity =.5
)

trace4 = go.Bar(
    x = parts_accessories.index,
    y = parts_accessories.id,
    name='Parts & Accessories',
    opacity =.5
)

trace5 = go.Bar(
    x = jewelry_watches.index,
    y = jewelry_watches.id,
    name='Jewelry & Watches',
    opacity =.5
)

PlotlyRequestError: Account limit reached: Your account is limited to creating 25 charts. To continue, you can override or delete existing charts or you can upgrade your account at: https://plot.ly/products/cloud

Help on function plot in module plotly.offline.offline:

plot(figure_or_data, show_link=False, link_text='Export to plot.ly', validate=True, output_type='file', include_plotlyjs=True, filename='temp-plot.html', auto_open=True, image=None, image_filename='plot_image', image_width=800, image_height=600, config=None, include_mathjax=False)
    Create a plotly graph locally as an HTML document or string.

    Example:
    ```
    from plotly.offline import plot
    import plotly.graph_objs as go

    plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html')
    # We can also download an image of the plot by setting the image parameter
    # to the image format we want
    plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html'
         image='jpeg')
    ```
    More examples below.

    figure_or_data -- a plotly.graph_objs.Figure or plotly.graph_objs.Data or
                      dict or list that describes a Plotly graph.
                      See https://plot.ly/python/ for examples of
                      graph descriptions.

    Keyword arguments:
    show_link (default=False) -- display a link in the bottom-right corner of
        of the chart that will export the chart to Plotly Cloud or
        Plotly Enterprise
    link_text (default='Export to plot.ly') -- the text of export link
    validate (default=True) -- validate that all of the keys in the figure
        are valid? omit if your version of plotly.js has become outdated
        with your version of graph_reference.json or if you need to include
        extra, unnecessary keys in your figure.
    output_type ('file' | 'div' - default 'file') -- if 'file', then
        the graph is saved as a standalone HTML file and `plot`
        returns None.
        If 'div', then `plot` returns a string that just contains the
        HTML <div> that contains the graph and the script to generate the
        graph.
        Use 'file' if you want to save and view a single graph at a time
        in a standalone HTML file.
        Use 'div' if you are embedding these graphs in an HTML file with
        other graphs or HTML markup, like a HTML report or an website.
    include_plotlyjs (True | False | 'cdn' | 'directory' | path - default=True)
        Specifies how the plotly.js library is included in the output html
        file or div string.

        If True, a script tag containing the plotly.js source code (~3MB)
        is included in the output.  HTML files generated with this option are
        fully self-contained and can be used offline.

        If 'cdn', a script tag that references the plotly.js CDN is included
        in the output. HTML files generated with this option are about 3MB
        smaller than those generated with include_plotlyjs=True, but they
        require an active internet connection in order to load the plotly.js
        library.

        If 'directory', a script tag is included that references an external
        plotly.min.js bundle that is assumed to reside in the same
        directory as the HTML file.  If output_type='file' then the
        plotly.min.js bundle is copied into the directory of the resulting
        HTML file. If a file named plotly.min.js already exists in the output
        directory then this file is left unmodified and no copy is performed.
        HTML files generated with this option can be used offline, but they
        require a copy of the plotly.min.js bundle in the same directory.
        This option is useful when many figures will be saved as HTML files in
        the same directory because the plotly.js source code will be included
        only once per output directory, rather than once per output file.

        If a string that ends in '.js', a script tag is included that
        references the specified path. This approach can be used to point
        the resulting HTML file to an alternative CDN.

        If False, no script tag referencing plotly.js is included. This is
        useful when output_type='div' and the resulting div string will be
        placed inside an HTML document that already loads plotly.js.  This
        option is not advised when output_type='file' as it will result in
        a non-functional html file.
    filename (default='temp-plot.html') -- The local filename to save the
        outputted chart to. If the filename already exists, it will be
        overwritten. This argument only applies if `output_type` is 'file'.
    auto_open (default=True) -- If True, open the saved file in a
        web browser after saving.
        This argument only applies if `output_type` is 'file'.
    image (default=None |'png' |'jpeg' |'svg' |'webp') -- This parameter sets
        the format of the image to be downloaded, if we choose to download an
        image. This parameter has a default value of None indicating that no
        image should be downloaded. Please note: for higher resolution images
        and more export options, consider making requests to our image servers.
        Type: `help(py.image)` for more details.
    image_filename (default='plot_image') -- Sets the name of the file your
        image will be saved to. The extension should not be included.
    image_height (default=600) -- Specifies the height of the image in `px`.
    image_width (default=800) -- Specifies the width of the image in `px`.
    config (default=None) -- Plot view options dictionary. Keyword arguments
        `show_link` and `link_text` set the associated options in this
        dictionary if it doesn't contain them already.
    include_mathjax (False | 'cdn' | path - default=False) --
        Specifies how the MathJax.js library is included in the output html
        file or div string.  MathJax is required in order to display labels
        with LaTeX typesetting.

        If False, no script tag referencing MathJax.js will be included in the
        output. HTML files generated with this option will not be able to
        display LaTeX typesetting.

        If 'cdn', a script tag that references a MathJax CDN location will be
        included in the output.  HTML files generated with this option will be
        able to display LaTeX typesetting as long as they have internet access.

        If a string that ends in '.js', a script tag is included that
        references the specified path. This approach can be used to point the
        resulting HTML file to an alternative CDN.