In [1]:
import pandas as pd
import numpy as np

import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode

In [15]:
df = pd.read_csv('home_page_list.csv')
df.applies_to_date = pd.to_datetime(df.applies_to_date)

watch_yourself = df[df.user_items_list_id == 163479]

,id,user_items_list_id,applies_to_date,view_count,view_score,purchase_item_count,clickthrough_count,featured_count,created_at,updated_at,comment_count
2081,1633215,163479,2019-01-11,12,0,0,0,0,1/11/19 12:58,1/11/19 12:58,0
2082,1633230,163479,2019-01-12,22,0,0,5,0,1/12/19 3:47,1/12/19 3:47,1
2083,1633285,163479,2019-01-13,59,0,0,12,0,1/13/19 0:00,1/13/19 0:00,0
2084,1633351,163479,2019-01-14,50,0,1,7,0,1/14/19 4:15,1/14/19 4:15,0
2085,1633385,163479,2019-01-15,58,0,0,2,0,1/15/19 1:19,1/15/19 1:19,0
2086,1633468,163479,2019-01-16,42,0,0,6,0,1/16/19 0:43,1/16/19 0:43,0
2087,1633496,163479,2019-01-17,79,0,0,14,0,1/17/19 0:38,1/17/19 0:38,1
2088,1633531,163479,2019-01-18,73,0,0,2,0,1/18/19 0:35,1/18/19 0:35,0
2089,1633570,163479,2019-01-19,39,0,0,4,0,1/19/19 0:03,1/19/19 0:03,0
2090,1633609,163479,2019-01-20,60,0,0,2,0,1/20/19 1:49,1/20/19 1:49,0
2091,1633658,163479,2019-01-21,69,0,0,2,0,1/21/19 0:01,1/21/19 0:01,0
2092,1633724,163479,2019-01-22,74,0,0,6,0,1/22/19 1:40,1/22/19 1:40,0
2093,1633757,163479,2019-01-23,78,0,0,2,0,1/23/19 0:00,1/23/19 0:00,0
2094,1633802,163479,2019-01-24,131,0,0,7,0,1/24/19 0:25,1/24/19 0:25,0
2095,1633883,163479,2019-01-25,43,0,0,7,0,1/25/19 0:30,1/25/19 0:30,0
2096,1633940,163479,2019-01-26,29,0,0,2,0,1/26/19 2:41,1/26/19 2:41,0
2097,1633968,163479,2019-01-27,20,0,0,5,0,1/27/19 0:01,1/27/19 0:01,0
2098,1634026,163479,2019-01-28,23,0,0,2,0,1/28/19 4:25,1/28/19 4:25,0
2099,1634071,163479,2019-01-29,28,0,0,1,0,1/29/19 3:38,1/29/19 3:38,0
2100,1634115,163479,2019-01-30,34,0,0,1,0,1/30/19 0:44,1/30/19 0:44,0
2101,1634158,163479,2019-01-31,39,0,0,4,0,1/31/19 1:21,1/31/19 1:21,1
2102,1634187,163479,2019-02-01,52,0,0,5,0,2/1/19 0:08,2/1/19 0:08,0
2103,1634243,163479,2019-02-02,38,0,0,2,0,2/2/19 0:37,2/2/19 0:37,0
2104,1634281,163479,2019-02-03,31,0,0,1,0,2/3/19 1:09,2/3/19 1:09,0
2105,1634320,163479,2019-02-04,37,0,0,0,0,2/4/19 0:00,2/4/19 0:00,0
2106,1634381,163479,2019-02-05,36,0,0,0,0,2/5/19 0:00,2/5/19 0:00,0
2107,1634440,163479,2019-02-06,9,0,0,5,0,2/6/19 3:18,2/6/19 3:18,0
2108,1634475,163479,2019-02-07,16,0,0,2,0,2/7/19 1:05,2/7/19 1:05,0
2109,1634512,163479,2019-02-08,16,0,0,4,0,2/8/19 0:08,2/8/19 0:08,0
2110,1634547,163479,2019-02-09,31,0,0,1,0,2/9/19 1:13,2/9/19 1:13,0
...,...,...,...,...,...,...,...,...,...,...,...
2121,1634972,163479,2019-02-19,19,0,0,3,0,2/19/19 0:38,2/19/19 0:38,0
2122,1635010,163479,2019-02-20,38,0,0,3,0,2/20/19 1:06,2/20/19 1:06,0
2123,1635048,163479,2019-02-21,31,0,0,2,0,2/21/19 2:01,2/21/19 2:01,0
2124,1635090,163479,2019-02-22,30,0,0,2,0,2/22/19 1:29,2/22/19 1:29,0
2125,1635131,163479,2019-02-23,33,0,0,2,0,2/23/19 4:12,2/23/19 4:12,0
2126,1635161,163479,2019-02-24,26,0,0,10,0,2/24/19 0:47,2/24/19 0:47,0
2127,1635198,163479,2019-02-25,28,0,0,2,0,2/25/19 1:13,2/25/19 1:13,0
2128,1635266,163479,2019-02-26,21,0,0,4,0,2/26/19 1:48,2/26/19 1:48,0
2129,1635320,163479,2019-02-27,24,0,0,2,0,2/27/19 3:31,2/27/19 3:31,0
2130,1635357,163479,2019-02-28,26,0,0,3,0,2/28/19 1:25,2/28/19 1:25,0
2131,1635395,163479,2019-03-01,29,0,0,3,0,3/1/19 1:56,3/1/19 1:56,0
2132,1635439,163479,2019-03-02,24,0,0,5,0,3/2/19 2:43,3/2/19 2:43,0
2133,1635481,163479,2019-03-03,23,0,0,5,0,3/3/19 2:52,3/3/19 2:52,0
2134,1635521,163479,2019-03-04,49,0,0,6,0,3/4/19 0:42,3/4/19 0:42,0
2135,1635567,163479,2019-03-05,103,0,0,14,0,3/5/19 2:19,3/5/19 2:19,0
2136,1635621,163479,2019-03-06,52,0,0,6,0,3/6/19 2:12,3/6/19 2:12,0
2137,1635658,163479,2019-03-07,16,0,0,2,0,3/7/19 1:17,3/7/19 1:17,0
2138,1635700,163479,2019-03-08,55,0,0,8,0,3/8/19 0:35,3/8/19 0:35,0
2139,1635732,163479,2019-03-09,31,0,0,0,0,3/9/19 0:03,3/9/19 0:03,0
2140,1635793,163479,2019-03-10,36,0,0,1,0,3/10/19 1:42,3/10/19 1:42,0
2141,1635838,163479,2019-03-11,20,0,0,3,0,3/11/19 3:39,3/11/19 3:39,0
2142,1635870,163479,2019-03-12,31,0,0,4,0,3/12/19 0:31,3/12/19 0:31,0
2143,1635911,163479,2019-03-13,28,0,0,9,0,3/13/19 0:34,3/13/19 0:34,0
2144,1635985,163479,2019-03-14,29,0,0,3,0,3/14/19 0:44,3/14/19 0:44,0
2145,1636044,163479,2019-03-15,28,0,0,2,0,3/15/19 0:14,3/15/19 0:14,0
2146,1636083,163479,2019-03-16,21,0,0,5,0,3/16/19 0:28,3/16/19 0:28,0
2147,1636131,163479,2019-03-17,46,0,0,1,0,3/17/19 0:47,3/17/19 0:47,0
2148,1636283,163479,2019-03-18,27,0,0,3,0,3/18/19 0:52,3/18/19 0:52,0
2149,1636324,163479,2019-03-19,26,0,0,2,0,3/19/19 0:53,3/19/19 0:53,0
2150,1636370,163479,2019-03-20,18,0,0,1,0,3/20/19 0:13,3/20/19 0:13,0

In [ ]:
trace_high = go.Scatter(
                x=df.applies_to_date,
                y=df['AAPL.High'],
                name = "AAPL High",
                line = dict(color = '#17BECF'),
                opacity = 0.8)